[LightMode]
# 覆盖默认值
OverrideDefault=True
# 高亮颜色
HighlightColor=#dcdcdc
# 悬停时高亮颜色
HighlightHoverColor=#eaeaea
# 高亮文本颜色
HighlightTextColor=#191919
# 按下时高亮文本颜色
HighlightTextPressColor=#4e4e4e
# 高亮标签颜色
HighlightLabelColor=#151515
# 高亮注释颜色
HighlightCommentColor=#151515
# 高亮标记颜色
HighlightMarkColor=#b4b0a7
# 面板颜色
PanelColor=#eaeaea
# 文本颜色
TextColor=#2a2a2a
# 标签颜色
LabelColor=#151515
# 注释颜色
CommentColor=#414141
# 翻页按钮颜色
PagingButtonColor=#151515
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#aaaaaa
# 指示文本颜色
AuxColor=#2a2a2a
# 光标前的预编辑颜色
PreeditColorPreCaret=#2a2a2a
# 预编辑光标颜色
PreeditColorCaret=#2a2a2a
# 光标后的预编辑颜色
PreeditColorPostCaret=#2a2a2a
# 边框颜色
BorderColor=#dcdcdce9
# 分隔线颜色
DividerColor=#cccccc

[DarkMode]
# 覆盖默认值
OverrideDefault=True
# 与浅色模式相同
SameWithLightMode=False
# 高亮颜色
HighlightColor=#3a3a3a
# 悬停时高亮颜色
HighlightHoverColor=#353535
# 高亮文本颜色
HighlightTextColor=#eaeaea
# 按下时高亮文本颜色
HighlightTextPressColor=#c0c0c0
# 高亮标签颜色
HighlightLabelColor=#eaeaea
# 高亮注释颜色
HighlightCommentColor=#eaeaea
# 高亮标记颜色
HighlightMarkColor=#dad5c8
# 面板颜色
PanelColor=#2a2a2a
# 文本颜色
TextColor=#eaeaea
# 标签颜色
LabelColor=#eaeaea
# 注释颜色
CommentColor=#eaeaea
# 翻页按钮颜色
PagingButtonColor=#dcdcdc
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#5d5d5d
# 指示文本颜色
AuxColor=#eaeaea
# 光标前的预编辑颜色
PreeditColorPreCaret=#eaeaea
# 预编辑光标颜色
PreeditColorCaret=#eaeaea
# 光标后的预编辑颜色
PreeditColorPostCaret=#eaeaea
# 边框颜色
BorderColor=#191919d3
# 分隔线颜色
DividerColor=#353535

[Typography]
# Layout
Layout=Vertical
# Writing mode
WritingMode="Horizontal top-bottom"
# Typography awareness for IM
TypographyAwarenessForIM=True
# Vertical comments align right
VerticalCommentsAlignRight=False
# Paging buttons style
PagingButtonsStyle=Arrow

[Background]
# Image
ImageUrl=
# Keep panel color when has image
KeepPanelColorWhenHasImage=False
# Blur
Blur=System
# Shadow
Shadow=True

[Font]
# Text font size
TextFontSize=16
# Text font weight
TextFontWeight=400
# Label font size
LabelFontSize=12
# Label font weight
LabelFontWeight=400
# Comment font size
CommentFontSize=12
# Comment font weight
CommentFontWeight=400
# Preedit font size
PreeditFontSize=16
# Preedit font weight
PreeditFontWeight=400

[Font/TextFontFamily]
0=

[Font/LabelFontFamily]
0=

[Font/CommentFontFamily]
0=

[Font/PreeditFontFamily]
0=

[Caret]
# Style
Style=Blink
# Text
Text=‸

[Highlight]
# Mark style
MarkStyle=None
# Mark text
MarkText=*
# Hover behavior
HoverBehavior=None

[Size]
# Override default
OverrideDefault=True
# Border width (px)
BorderWidth=1
# Border radius (px)
BorderRadius=8
# Margin (px)
Margin=2
# Highlight radius (px)
HighlightRadius=8
# Top padding (px)
TopPadding=3
# Right padding (px)
RightPadding=7
# Bottom padding (px)
BottomPadding=3
# Left padding (px)
LeftPadding=7
# Gap between label, text and comment (px)
LabelTextGap=6
# Vertical minimum width (px)
VerticalMinWidth=200
# Scroll cell width (px)
ScrollCellWidth=65
# Horizontal divider width (px)
HorizontalDividerWidth=1

