$env.XDG_CACHE_HOME = ($nu.home-path | path join '.cache') # "$HOME\.cache"
$env.XDG_CONFIG_HOME = ($nu.home-path | path join '.config') # "$HOME\.config"
$env.XDG_DATA_HOME = ($nu.home-path | path join '.local' 'share') # "$HOME\.local\share"
$env.XDG_STATE_HOME = ($nu.home-path | path join '.local' 'state') # "$HOME\.local\state"
$env.XDG_BIN_HOME = ($nu.home-path | path join '.local' 'bin') # "$HOME\.local\bin"
