# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json

gui:
  theme:
    activeBorderColor:
      - "#cccccc"
      - bold
    inactiveBorderColor:
      - "#5d5d5d"
    selectedLineBgColor:
      - "#2a2a2a"
    optionsTextColor:
      - "#4e4e4e"
